{
  "id": "WORC_Example_STWStrategyHN_Multiclass___plot_ranked_percentages___all",
  "hostinfo": {
    "os": {
      "system": "Windows",
      "is64bits": 1,
      "maxsize": 9223372036854775807,
      "version": {
        "release": "10",
        "version": "10.0.19045",
        "servicepack": "SP0",
        "ptype": "Multiprocessor Free"
      }
    },
    "uname": [
      "Windows",
      "WX-4CD717106C11",
      "10",
      "10.0.19045",
      "AMD64",
      "Intel64 Family 6 Model 186 Stepping 2, GenuineIntel"
    ],
    "username": "795023",
    "cwd": "C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\tests",
    "python": {
      "version": "3.11.5",
      "branch": "",
      "compiler": "MSC v.1936 64 bit (AMD64)",
      "implementation": "CPython",
      "revision": ""
    },
    "envvar": {
      "ADM_WX-COMPUTERS": "YES",
      "ALLUSERSPROFILE": "C:\\ProgramData",
      "AMBUVIEWLPZSCHIPHOLBORD": "NO",
      "AMBUVIEWSCHIPHOLBORD": "NO",
      "APPDATA": "C:\\Users\\795023\\AppData\\Roaming",
      "APPSENSE_COMPUTERS_NO_FOLDER_REDIRECTION": "NO",
      "APPSENSE_NO_FOLDER_REDIRECTION_FOR_ALLUSERS_ON_WORKSTATIONS": "NO",
      "APPSENSE_USERS_NO_FOLDER_REDIRECTION": "NO",
      "APPV_CONTENT_STORE_ROOT": "appvcs.erasmusmc.nl",
      "ASCOMUNITEVIEW": "NO",
      "AS_PLATFORM": "LAPTOP",
      "BITLOCKERUSBEXCEPTION": "NO",
      "BIZPLAY": "NO",
      "BUILDDIR": "_build",
      "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
      "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
      "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
      "COMPUTERDOMAIN": "erasmusmc",
      "COMPUTERNAME": "WX-4CD717106C11",
      "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
      "CONDA_DEFAULT_ENV": "WORCTestInstall",
      "CONDA_EXE": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\Scripts\\conda.exe",
      "CONDA_EXES": "\"C:\\Users\\795023\\AppData\\Local\\anaconda3\\condabin\\..\\Scripts\\conda.exe\"  ",
      "CONDA_PREFIX": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall",
      "CONDA_PREFIX_1": "C:\\Users\\795023\\AppData\\Local\\anaconda3",
      "CONDA_PROMPT_MODIFIER": "(WORCTestInstall) ",
      "CONDA_PYTHON_EXE": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\python.exe",
      "CONDA_SHLVL": "2",
      "DESKTOP_BEHEER": "C:\\ProgramData\\Desktop_Beheer",
      "DESKTOP_BEHEER_SOURCE": "\\\\storage.erasmusmc.nl\\s\\apps$\\SOM",
      "DOCENT": "NO",
      "DOMAINONLINE": "YES",
      "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData",
      "DXSDK_DIR": "C:\\Program Files (x86)\\Microsoft DirectX SDK (August 2009)\\",
      "FLEXWERKPLEK": "NO",
      "GOPATH": "C:\\Users\\795023\\go",
      "HIXACCLOKAAL": "NO",
      "HIXDIAGNOSTIEK": "NO",
      "HIXFRAMEGRABBER": "NO",
      "HIXGOLDMANSCANNER": "NO",
      "HIXMEEKIJKMONITOR": "NO",
      "HIXOPLEIDINGEN": "NO",
      "HIXSCHIPHOLBORD": "NO",
      "HIXSPECIAL": "NO",
      "HIXSPEECHMIKE": "NO",
      "HIXVERGADERRUIMTEWERKPLEK": "NO",
      "HIXWEBCAM": "NO",
      "HIXWEEGSCHAAL": "NO",
      "HIXWIRELESS": "NO",
      "HIXWIRELESSTYPE": "NotSpecified",
      "HIX_CONTENT_STORE_ROOT": "hixcs.erasmusmc.nl",
      "HOMEDRIVE": "U:",
      "HOMEPATH": "\\",
      "HOMESHARE": "\\\\storage.erasmusmc.nl\\u\\user\\795023",
      "IVANTISYSTEMCONTROLSEXCEPTION": "NO",
      "KMP_DUPLICATE_LIB_OK": "True",
      "KMP_INIT_AT_FORK": "FALSE",
      "LOCALAPPDATA": "C:\\Users\\795023\\AppData\\Local",
      "LOGONSERVER": "\\\\DC5",
      "MDOWERKPLEK": "NO",
      "METINGENDRIVER": "NO",
      "MWPSUBTYPE": "NotSpecified",
      "MWPTYPE": "NotSpecified",
      "NARROWCASTING": "NO",
      "NETBIOS_DOMAINNAME": "ERASMUSMC",
      "NUMBER_OF_PROCESSORS": "20",
      "OFFICEMODERNAUTHENTICATIONEXCEPTION": "NO",
      "OKPLANNINGVIEWERSCHIPHOLBORD": "NO",
      "OS": "Windows_NT",
      "PATH": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall;C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Library\\mingw-w64\\bin;C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Library\\usr\\bin;C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Library\\bin;C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Scripts;C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\bin;C:\\Users\\795023\\AppData\\Local\\anaconda3\\condabin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit;C:\\Program Files\\dotnet;C:\\Program Files\\Go\\bin;C:\\Oracle\\instantclient_19_12;C:\\Program Files\\Zabbix Agent 2;C:\\Users\\795023\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\795023\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\795023\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin;C:\\Users\\795023\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\795023\\AppData\\Local\\Programs\\Git\\cmd;C:\\Program Files (x86)\\Hugo;C:\\Users\\795023\\go\\bin",
      "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
      "PRINTTOOLCLIENTNAME": "WX-4CD717106C11_00000000",
      "PROCESSOR_ARCHITECTURE": "AMD64",
      "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 186 Stepping 2, GenuineIntel",
      "PROCESSOR_LEVEL": "6",
      "PROCESSOR_REVISION": "ba02",
      "PROGRAMDATA": "C:\\ProgramData",
      "PROGRAMFILES": "C:\\Program Files",
      "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
      "PROGRAMW6432": "C:\\Program Files",
      "PROMPT": "(WORCTestInstall) $P$G",
      "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
      "PUBLIC": "C:\\Users\\Public",
      "RUBODICOMVIEWER": "C:\\Program Files (x86)\\DICOMviewer",
      "SCREENSAVER": "10",
      "SCREENSAVERTYPE": "NetPresenter",
      "SEHPOPUPSCHIPHOLBORD": "NO",
      "SESSIONNAME": "Console",
      "SOURCEDIR": ".",
      "SPHINXBUILD": "sphinx-build",
      "SSL_CERT_DIR": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Library\\ssl\\certs",
      "SSL_CERT_FILE": "C:\\Users\\795023\\AppData\\Local\\anaconda3\\Library\\ssl\\cacert.pem",
      "STARTMENU": "C:\\Users\\795023\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs",
      "SUG101": "NO",
      "SYSTEMDRIVE": "C:",
      "SYSTEMROOT": "C:\\WINDOWS",
      "TEMP": "C:\\Users\\795023\\AppData\\Local\\Temp",
      "TMP": "C:\\Users\\795023\\AppData\\Local\\Temp",
      "TNS_ADMIN": "S:\\Oracle\\Ora81\\Network\\Admin",
      "UATDATA": "C:\\WINDOWS\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77",
      "UA_USERS": "YES",
      "USERDNSDOMAIN": "ERASMUSMC.NL",
      "USERDOMAIN": "ERASMUSMC",
      "USERDOMAIN_ROAMINGPROFILE": "ERASMUSMC",
      "USERHOMEDRIVE": "U:\\",
      "USERNAME": "795023",
      "USERPROFILE": "C:\\Users\\795023",
      "VDI_ENDPOINT": "NO",
      "WINDIR": "C:\\WINDOWS",
      "WSUSVOORLOPER": "NO",
      "ZEBRAZD420_INSTALLED": "NO",
      "ZES_ENABLE_SYSMAN": "1",
      "__CONDA_OPENSLL_CERT_FILE_SET": "\"1\"",
      "__CONDA_OPENSSL_CERT_DIR_SET": "1"
    },
    "drmaa": {
      "jobid": null,
      "taskid": null,
      "jobname": null
    }
  },
  "sysinfo_start": {
    "cpu_usage": {
      "user": 102150.015625,
      "system": 66620.5625,
      "idle": 3925089.90625,
      "interrupt": 6105.203125,
      "dpc": 2955.15625,
      "percent": 36.1
    },
    "memory_usage": {
      "virtual": {
        "total": 34029125632,
        "available": 13280026624,
        "percent": 61.0,
        "used": 20749099008,
        "free": 13280026624
      },
      "swap": {
        "total": 34359738368,
        "used": 1207291904,
        "free": 33152446464,
        "percent": 3.5,
        "sin": 0,
        "sout": 0
      }
    },
    "mounts": [
      {
        "device": "C:\\",
        "mountpoint": "C:\\",
        "fstype": "NTFS",
        "opts": "rw,fixed",
        "disk_total": 1013633249280,
        "disk_used": 304228106240,
        "disk_free": 709405143040,
        "disk_use_percent": 30.0
      }
    ],
    "users": [
      {
        "name": "795023",
        "terminal": null,
        "host": null,
        "started": 1752468422.705306,
        "pid": null
      }
    ]
  },
  "process": {
    "return_code": 0,
    "stdout": " [WARNING]  __init__:0082 >> Not running in a production installation (branch \"unknown\" from installed package)\n[INFO] LightGBM classifier currently not available. Please see https://worc.readthedocs.io/en/latest/static/additionalfunctionality.html.\n[INFO] Bayesian optimization through SMAC functionality currently not available. Please see https://worc.readthedocs.io/en/latest/static/additionalfunctionality.html.\nDetermining score per patient.\nLabel names to extract: ['imaginary_label_1', 'complement_label_1']\n[WORC Warning] Support for multiple label types not supported yet. Taking first label for plot_estimator_performance.\n\n\nCross-validation 1 / 3.\nFinal ensemble validation score: 0.8833333333333333\nRefitting estimator 1 / 1.\n\n\nTruth: [[0. 1.]\n [1. 0.]\n [0. 1.]\n [1. 0.]]\nPrediction: [[1. 0.]\n [1. 0.]\n [1. 0.]\n [1. 0.]]\nScore: [[0.5961801  0.38882496]\n [0.6422619  0.35850148]\n [0.61395278 0.37687392]\n [0.59663898 0.38848462]]\nComputing performance statistics.\nAUC: 0.75\n\n\nCross-validation 2 / 3.\nFinal ensemble validation score: 0.8833333333333333\nRefitting estimator 1 / 1.\n\n\nTruth: [[0. 1.]\n [0. 1.]\n [1. 0.]\n [1. 0.]]\nPrediction: [[1. 0.]\n [1. 0.]\n [1. 0.]\n [1. 0.]]\nScore: [[0.71526338 0.30793772]\n [0.67681994 0.33783343]\n [0.60198507 0.38695144]\n [0.64924627 0.35572393]]\nComputing performance statistics.\nAUC: 0.0\n\n\nCross-validation 3 / 3.\nFinal ensemble validation score: 0.75\nRefitting estimator 1 / 1.\n\n\nTruth: [[0. 1.]\n [0. 1.]\n [1. 0.]\n [1. 0.]]\nPrediction: [[1. 0.]\n [0. 1.]\n [1. 0.]\n [0. 1.]]\nScore: [[0.90698605 0.25257436]\n [0.3965235  0.45681627]\n [0.81414569 0.30673113]\n [0.28305662 0.5       ]]\nComputing performance statistics.\nAUC: 0.25\nAlways Wrong: HN1004, label 0.0.\nAlways Right: HN1146, label 1.0.\nAlways Wrong: HN1331, label 0.0.\nAlways Right: HN1372, label 1.0.\nAlways Wrong: HN1077, label 0.0.\nAlways Right: HN1524, label 1.0.\nAlways Wrong: HN1339, label 0.0.\nAlways Right: HN1519, label 1.0.\nAlways Wrong: HN1560, label 1.0.\nAUC 95%: : 0.3333333333333333 (-0.9216070461613746, 1.588273712828041).\nAUC_complement_label_1 95%: : 0.5 (0.5, 0.5).\nAUC_imaginary_label_1 95%: : 0.16666666666666666 (-0.7819790917207673, 1.1153124250541007).\nAccuracy 95%: : 0.5 (0.5, 0.5).\nAccuracy_complement_label_1 95%: : 0.5 (0.5, 0.5).\nAccuracy_imaginary_label_1 95%: : 0.5 (0.5, 0.5).\nAverage Accuracy 95%: : 0.5 (0.5, 0.5).\nBCA_complement_label_1 95%: : 0.5 (0.5, 0.5).\nBCA_imaginary_label_1 95%: : 0.5 (0.5, 0.5).\nF1-score 95%: : 0.38888888888888884 (0.07267363609307748, 0.7051041416847001).\nF1-score_complement_label_1 95%: : 0.16666666666666666 (-0.7819790917207673, 1.1153124250541007).\nF1-score_imaginary_label_1 95%: : 0.5 (0.5, 0.5).\nNPV 95%: : 0.3333333333333333 (-0.1409895458603836, 0.8076562125270502).\nNPV_complement_label_1 95%: : 0.38888888888888884 (0.07267363609307748, 0.7051041416847001).\nNPV_imaginary_label_1 95%: : 0.38888888888888884 (0.07267363609307748, 0.7051041416847001).\nPrecision 95%: : 0.3333333333333333 (-0.1409895458603836, 0.8076562125270502).\nPrecision_complement_label_1 95%: : 0.3333333333333333 (-0.9216070461613746, 1.588273712828041).\nPrecision_imaginary_label_1 95%: : 0.3333333333333333 (-0.9216070461613746, 1.588273712828041).\nSensitivity 95%: : 0.5 (0.5, 0.5).\nSensitivity_complement_label_1 95%: : 0.16666666666666666 (-0.7819790917207673, 1.1153124250541007).\nSensitivity_imaginary_label_1 95%: : 0.8333333333333334 (-0.11531242505410044, 1.7819790917207672).\nSpecificity 95%: : 0.5 (0.5, 0.5).\nSpecificity_complement_label_1 95%: : 0.8333333333333334 (-0.11531242505410044, 1.7819790917207672).\nSpecificity_imaginary_label_1 95%: : 0.16666666666666666 (-0.7819790917207673, 1.1153124250541007).\nWriting output scores to CSV.\n",
    "stderr": "--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 538, in plot_estimator_performance\n    performances = compute_statistics(y_truth, y_score, y_prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 113, in compute_statistics\n    metrics.performance_multilabel(y_truth,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\classification\\metrics.py\", line 184, in performance_multilabel\n    Precision = TP/(TP+FP)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\Documents\\\\GitHub\\\\WORC\\\\WORC\\\\classification\\\\metrics.py:184: RuntimeWarning: invalid value encountered in divide\\n  Precision = TP/(TP+FP)\\n'\nArguments: ()\n--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 538, in plot_estimator_performance\n    performances = compute_statistics(y_truth, y_score, y_prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 113, in compute_statistics\n    metrics.performance_multilabel(y_truth,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\classification\\metrics.py\", line 189, in performance_multilabel\n    NPV = TN/(TN+FN)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\Documents\\\\GitHub\\\\WORC\\\\WORC\\\\classification\\\\metrics.py:189: RuntimeWarning: invalid value encountered in divide\\n  NPV = TN/(TN+FN)\\n'\nArguments: ()\n--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 538, in plot_estimator_performance\n    performances = compute_statistics(y_truth, y_score, y_prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 113, in compute_statistics\n    metrics.performance_multilabel(y_truth,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\classification\\metrics.py\", line 184, in performance_multilabel\n    Precision = TP/(TP+FP)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\Documents\\\\GitHub\\\\WORC\\\\WORC\\\\classification\\\\metrics.py:184: RuntimeWarning: invalid value encountered in divide\\n  Precision = TP/(TP+FP)\\n'\nArguments: ()\n--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 538, in plot_estimator_performance\n    performances = compute_statistics(y_truth, y_score, y_prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 113, in compute_statistics\n    metrics.performance_multilabel(y_truth,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\classification\\metrics.py\", line 189, in performance_multilabel\n    NPV = TN/(TN+FN)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\Documents\\\\GitHub\\\\WORC\\\\WORC\\\\classification\\\\metrics.py:189: RuntimeWarning: invalid value encountered in divide\\n  NPV = TN/(TN+FN)\\n'\nArguments: ()\n--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 713, in plot_estimator_performance\n    stats[f\"{name} 95%:\"] = f\"{np.nanmean(perf)} {str(compute_confidence(perf, N_1, N_2, alpha))}\"\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\statistics\\compute_CI.py\", line 69, in compute_confidence\n    CI = st.t.interval(alpha, N_iterations-1, loc=metric_average, scale=metric_std)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\site-packages\\scipy\\stats\\_distn_infrastructure.py\", line 1505, in interval\n    a = self.ppf(q1, *args, **kwds)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\site-packages\\scipy\\stats\\_distn_infrastructure.py\", line 2323, in ppf\n    lower_bound = _a * scale + loc\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\WORCTestInstall\\\\Lib\\\\site-packages\\\\scipy\\\\stats\\\\_distn_infrastructure.py:2323: RuntimeWarning: invalid value encountered in multiply\\n  lower_bound = _a * scale + loc\\n'\nArguments: ()\n--- Logging error ---\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 449, in format\n    return self._format(record)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 445, in _format\n    return self._fmt % values\n           ~~~~~~~~~~^~~~~~~~\nKeyError: 'tracking_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 1110, in emit\n    msg = self.format(record)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 953, in format\n    return fmt.format(record)\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 690, in format\n    s = self.formatMessage(record)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n    return self._style.format(record)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\logging\\__init__.py\", line 451, in format\n    raise ValueError('Formatting field not found in record: %s' % e)\nValueError: Formatting field not found in record: 'tracking_id'\nCall stack:\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 103, in <module>\n    main()\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py\", line 90, in main\n    plot_ranked_scores(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 470, in plot_ranked_scores\n    plot_ranked_percentages(estimator=estimator,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_ranked_scores.py\", line 137, in plot_ranked_percentages\n    plot_estimator_performance(prediction,\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\plotting\\plot_estimator_performance.py\", line 713, in plot_estimator_performance\n    stats[f\"{name} 95%:\"] = f\"{np.nanmean(perf)} {str(compute_confidence(perf, N_1, N_2, alpha))}\"\n  File \"C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\statistics\\compute_CI.py\", line 69, in compute_confidence\n    CI = st.t.interval(alpha, N_iterations-1, loc=metric_average, scale=metric_std)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\site-packages\\scipy\\stats\\_distn_infrastructure.py\", line 1505, in interval\n    a = self.ppf(q1, *args, **kwds)\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\site-packages\\scipy\\stats\\_distn_infrastructure.py\", line 2324, in ppf\n    upper_bound = _b * scale + loc\n  File \"C:\\Users\\795023\\AppData\\Local\\anaconda3\\envs\\WORCTestInstall\\Lib\\warnings.py\", line 109, in _showwarnmsg\n    sw(msg.message, msg.category, msg.filename, msg.lineno,\nMessage: 'C:\\\\Users\\\\795023\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\WORCTestInstall\\\\Lib\\\\site-packages\\\\scipy\\\\stats\\\\_distn_infrastructure.py:2324: RuntimeWarning: invalid value encountered in multiply\\n  upper_bound = _b * scale + loc\\n'\nArguments: ()\n",
    "command": [
      "python",
      "C:\\Users\\795023\\Documents\\GitHub\\WORC\\WORC\\resources\\fastr_tools\\worc\\bin\\PlotRankedScores.py",
      "--estimator",
      "C:\\Users\\795023\\documents\\github\\worc\\worc\\tests\\worc_example_stwstrategyhn_multiclass\\classify\\all\\classification_0.hdf5",
      "--output_zip",
      "C:\\Users\\795023\\documents\\github\\worc\\worc\\tests\\worc_example_stwstrategyhn_multiclass\\plot_ranked_percentages\\all\\output_zip_0.zip",
      "--output_csv",
      "C:\\Users\\795023\\documents\\github\\worc\\worc\\tests\\worc_example_stwstrategyhn_multiclass\\plot_ranked_percentages\\all\\output_csv_0.csv",
      "--pinfo",
      "C:\\Users\\795023\\Documents\\GitHub\\WORCTutorial\\Data\\Examplefiles\\pinfo_HN.csv",
      "--ensemble_method",
      "Single",
      "--ensemble_size",
      "100",
      "--label_type",
      "imaginary_label_1, complement_label_1",
      "--scores",
      "percentages"
    ],
    "resource_usage": [
      {
        "timestamp": "2025-07-30T14:48:53.437819",
        "cpu_percent": 42.2,
        "vmem": 24379392,
        "rmem": 34693120,
        "read_bytes": 5803656,
        "write_bytes": 39776
      },
      {
        "timestamp": "2025-07-30T14:48:54.438155",
        "cpu_percent": 89.1,
        "vmem": 62316544,
        "rmem": 73560064,
        "read_bytes": 22015886,
        "write_bytes": 39780
      },
      {
        "timestamp": "2025-07-30T14:48:55.438557",
        "cpu_percent": 96.9,
        "vmem": 736354304,
        "rmem": 116133888,
        "read_bytes": 34177419,
        "write_bytes": 39893
      },
      {
        "timestamp": "2025-07-30T14:48:56.439182",
        "cpu_percent": 93.8,
        "vmem": 1446858752,
        "rmem": 198524928,
        "read_bytes": 52856440,
        "write_bytes": 39893
      },
      {
        "timestamp": "2025-07-30T14:48:57.439865",
        "cpu_percent": 87.5,
        "vmem": 1497305088,
        "rmem": 262922240,
        "read_bytes": 68832337,
        "write_bytes": 52986
      },
      {
        "timestamp": "2025-07-30T14:48:58.440246",
        "cpu_percent": 79.7,
        "vmem": 1530363904,
        "rmem": 298000384,
        "read_bytes": 78315351,
        "write_bytes": 79539
      },
      {
        "timestamp": "2025-07-30T14:48:59.441040",
        "cpu_percent": 0.0,
        "vmem": 1530363904,
        "rmem": 298000384,
        "read_bytes": 78315351,
        "write_bytes": 79539
      }
    ],
    "time_elapsed": 7.743281841278076
  },
  "sysinfo_end": {
    "cpu_usage": {
      "user": 102184.015625,
      "system": 66648.296875,
      "idle": 3925197.2343749995,
      "interrupt": 6105.53125,
      "dpc": 2955.1875,
      "percent": 36.7
    },
    "memory_usage": {
      "virtual": {
        "total": 34029125632,
        "available": 10375782400,
        "percent": 69.5,
        "used": 23653343232,
        "free": 10375782400
      },
      "swap": {
        "total": 34359738368,
        "used": 1207267328,
        "free": 33152471040,
        "percent": 3.5,
        "sin": 0,
        "sout": 0
      }
    },
    "mounts": [
      {
        "device": "C:\\",
        "mountpoint": "C:\\",
        "fstype": "NTFS",
        "opts": "rw,fixed",
        "disk_total": 1013633249280,
        "disk_used": 304232599552,
        "disk_free": 709400649728,
        "disk_use_percent": 30.0
      }
    ],
    "users": [
      {
        "name": "795023",
        "terminal": null,
        "host": null,
        "started": 1752468422.705306,
        "pid": null
      }
    ]
  }
}